spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.100:3306/springboot?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
mybatis:
  type-aliases-package: com.example.demo.domain
  mapper-locations:
    - classpath:mapper/*Mapper.xml